models:
  naive_mean:
    enabled: true
    params: null  # No parameters needed

  persistence:
    enabled: true
    params:
      K: 1  # Last value prediction

  naive_seasonal:
    enabled: true
    params:
      K: 7  # Weekly seasonality

  naive_drift:
    enabled: true
    params: null  # No parameters needed

  naive_moving_average:
    enabled: true
    params:
      input_chunk_length: 7  # Window size for moving average

paths:
  model_save_dir: "models/saved/baseline"
  predictions_dir: "data/predictions/baseline"
  evaluation_file: "results/baseline_evaluation.csv"