# config/model_configs/baseline_models.yaml
model_type: "baseline"
requires_optimization: false
logging:
  metrics: ["mae", "rmse"]
  log_predictions: true
  log_data_stats: true

models:
  naive_mean:
    enabled: true
    params: null  # No parameters needed

  persistence:
    enabled: true
    params:
      K: 1  # Last value prediction

  naive_seasonal:
    enabled: true
    params:
      K: 7  # Weekly seasonality

  naive_drift:
    enabled: true
    params: null  # No parameters needed

  naive_moving_average:
    enabled: true
    params:
      input_chunk_length: 7  # Window size for moving average

