# config/model_configs/deep_learning_models.yaml
common:
  # Global parameters for all models
  n_epochs: 100
#  n_epochs: 10
  batch_size: [32, 64]
  dropout: [0, 0.2, 0.4]
#  n_trials: 2
  n_trials: 50

  # Training configurations
  training:
    optimizer: "Adam"  # Options: ["Adam", "AdamW", "RMSprop", "SGD"]
    optimizer_kwargs:
      lr: [0.00001, 0.1]
#      lr: [0.0001, 0.001, 0.01]
#      weight_decay: [0.0, 0.1, 0.2]
    loss_fn: "MSE"  # Options: ["MSE", "MAE", "MAPE", "SMAPE"]
#    scheduler: "ReduceLROnPlateau"  # Options: ["ReduceLROnPlateau", "StepLR", "CosineAnnealingLR"]
#    scheduler_kwargs:
#      mode: "min"
#      patience: 10
#      factor: 0.1

  # Early stopping
  early_stopping:
    monitor: "val_loss"
    patience: 15
    min_delta: 0.001
    mode: "min"

  # Training length for RNN-based models (must be > input_chunk_length; = input_chunk_length + horizon)
  training_length: [48, 72, 96]

  # Lags and horizon configuration with step intervals
  input_chunk_length:
     min_length: 7
     max_length: 56
     step_size: 7

models:
  rnn:
    enabled: true
    hyperparameter_ranges:
      hidden_dim: [8, 16, 32]
      n_rnn_layers: [1, 2]

  lstm:
    enabled: true
    hyperparameter_ranges:
      hidden_dim: [8, 16, 32]
      n_rnn_layers: [1, 2]

  gru:
    enabled: true
    hyperparameter_ranges:
      hidden_dim: [8, 16, 32]
      n_rnn_layers: [1, 2]

  deepar:
    enabled: true
    hyperparameter_ranges:
      model: "LSTM"
      hidden_dim: [8, 16, 32]
      n_rnn_layers: [1, 2]
      likelihood: GaussianLikelihood()

  nbeats:
    enabled: true
    hyperparameter_ranges:
      generaic_architecture: True,
      num_stacks: [1]
      num_blocks: [30, 50]
      num_layers: [2, 4]
      layer_widths: [512]
#      expansion_coefficient_dim: [3, 5, 7, 9]
#      trend_polynomial_degree: [1, 2, 3, 4]

  nhits:
    enabled: true
    hyperparameter_ranges:
      num_stacks: [3]
      num_blocks: [1, 2]
      num_layers: [2, 4]
      layer_widths: [512]

  tcn:
    enabled: true
    hyperparameter_ranges:
      num_filters: [8, 16, 32]
      kernel_size: [3, 5]
      num_layers: [1, 2]
      dilation_base: [2, 4]


  transformer:
    enabled: true
    hyperparameter_ranges:
      d_model: [16, 32, 64]
      nhead: [2, 4]
      num_encoder_layers: [1, 2]
      num_decoder_layers: [1, 2]
      dim_feedforward: [256]

  tft:
    enabled: true
    hyperparameter_ranges:
      hidden_size: [8, 16, 32]
      lstm_layers: [1, 2]
      num_attention_heads: [1, 2]
#      hidden_continuous_size: [8, 16, 32]

  dlinear:
    enabled: true
    hyperparameter_ranges:
      kernel_size: [5, 15, 25, 35, 45]
#      individual: [ true, false ]
#      decomposition: [ 'moving_avg', 'trend' ]
#      window_size: [ 7, 14, 28 ]

  nlinear:
    enabled: true
    hyperparameter_ranges: null

