# config/model_configs/regression_models.yaml
common:
  lags:
    horizon_1:
      min_lag: 7
      max_lag: 14
    horizon_3:
      min_lag: 14
      max_lag: 28
    horizon_7:
      min_lag: 28
      max_lag: 56
  n_trials: 50

models:
  linear:
    enabled: true
    params: null

  random_forest:
    enabled: true
    hyperparameter_ranges:
      n_estimators: [100, 200, 300, 400, 500]
      max_depth: [3, 5, 7, 10]
      min_samples_split: [2, 5, 10]

  xgboost:
    enabled: true
    hyperparameter_ranges:
      n_estimators: [100, 200, 300, 400, 500]
      max_depth: [3, 5, 7, 10]
      learning_rate: [1e-5, 1e-4, 1e-3, 1e-2, 1e-1]
#      subsample: [0.6, 0.8, 1.0]
#      objective: "reg:squarederror"

  lightgbm:
    enabled: true
    hyperparameter_ranges:
      n_estimators: [100, 200, 300, 400, 500]
      num_leaves: [20, 30, 50, 100, 150]
      max_depth: [3, 5, 7, 10]
      min_child_samples: [5, 10, 20, 50, 100]
      learning_rate: [1e-5, 1e-4, 1e-3, 1e-2, 1e-1]

paths:
  model_save_dir: "models/saved/regression"
  predictions_dir: "data/predictions/regression"
  evaluation_file: "results/regression_evaluation.csv"