# config/model_configs/regression_models.yaml
common:
  lags:
    horizon_7:
      min_lag: 7
      max_lag: 56
      step_size: 7
    horizon_28:
      min_lag: 28
      max_lag: 84
      step_size: 7
#  n_trials: 2
  n_trials: 50


models:
  linear:
    enabled: true
    params: null

  random_forest:
    enabled: true
    hyperparameter_ranges:
      n_estimators: [100, 500]
#      max_depth: [3, 5, 7, 10]
#      min_samples_split: [2]

  xgboost:
    enabled: true
    hyperparameter_ranges:
      n_estimators: [100, 500]
      max_depth: [5, 10]
      learning_rate: [0.3, 0.1, 0.05]
#      subsample: [0.6, 0.8, 1.0]
#      objective: "reg:squarederror"

  lightgbm:
    enabled: true
    hyperparameter_ranges:
      n_estimators: [100, 500]
#      num_leaves: [20, 30, 50, 100, 150]
      max_depth: [5, 10]
#      min_child_samples: [5, 10, 20, 50, 100]
      learning_rate: [0.3, 0.1, 0.05]

