# config/model_configs/statistical_models.yaml
models:
  auto_arima:
    enabled: false
    params:
      seasonal: true
      m: 7  # Weekly seasonality
      start_p: 2
      start_q: 2
      max_p: 5
      max_q: 5
      d: 1
      D: 1
      seasonal_test: "ch"  # Use CH test for seasonal differencing
      trace: true
      error_action: "ignore"
      suppress_warnings: true

  exp_smoothing:
    enabled: true
    params:
      trend: "additive"      # ModelMode.ADDITIVE
      seasonal: "multiplicative"  # SeasonalityMode.MULTIPLICATIVE
      seasonal_periods: 7    # Weekly seasonality

  tbats:
    enabled: true
    params:
      n_jobs: 4  # Explicitly set to number of available CPUs
#      seasonal_periods: [ 7 ]
      use_arma_errors: true
      use_box_cox: false
      use_trend: true

  theta:
    enabled: true
    params:
      theta: 2
      season_mode: "additive"

  four_theta:
    enabled: true
    params:
      theta: 2
      season_mode: "additive"
      model_mode: "additive"

  prophet:
    enabled: false
    params:
      growth: "linear"
      seasonality_mode: "multiplicative"
      weekly_seasonality: true
      yearly_seasonality: true
      daily_seasonality: false
#      uncertainty_samples: 1000

common:
  seasonality: 7  # Weekly seasonality
  validation_criterion: "mae"
  n_jobs: -1  # Use all available cores for parallel processing

