# config/model_configs/statistical_models.yaml
models:
  auto_arima:
    enabled: true
    params:
      seasonal: true
      m: 7  # Weekly seasonality
      start_p: 2
      start_q: 2
      max_p: 5
      max_q: 5
      d: 1
      D: 1
      seasonal_test: "ch"  # Use CH test for seasonal differencing
      trace: true
      error_action: "ignore"
      suppress_warnings: true

  exp_smoothing:
    enabled: true
    params:
      trend: "additive"      # ModelMode.ADDITIVE
      seasonal: "multiplicative"  # SeasonalityMode.MULTIPLICATIVE
      seasonal_periods: 7    # Weekly seasonality
      damped: false

  tbats:
    enabled: true
    params:
      use_trend: true
      use_box_cox: false  # Box-Cox transformation handled separately
      seasonal_periods: [7]  # Weekly seasonality
      use_arma_errors: true
      n_jobs: -1  # Use all available cores

  theta:
    enabled: true
    params:
      theta: 2
      season_mode: "multiplicative"
      season_length: 7

  four_theta:
    enabled: true
    params:
      theta: 2
      season_mode: "multiplicative"
      season_length: 7
      model_mode: "multiplicative"

  prophet:
    enabled: true
    params:
      growth: "linear"
      seasonality_mode: "multiplicative"
      weekly_seasonality: true
      yearly_seasonality: "auto"
      daily_seasonality: false
      uncertainty_samples: 1000

common:
  seasonality: 7  # Weekly seasonality
  validation_criterion: "mae"
  n_jobs: -1  # Use all available cores for parallel processing

transformation:
  type: "box-cox"
  offset: 1
  epsilon: 1.0e-6

paths:
  model_save_dir: "models/saved/statistical"
  predictions_dir: "data/predictions/statistical"
  evaluation_file: "results/statistical_evaluation.csv"