program: train.py
method: bayes
metric:
  name: val_loss
  goal: minimize

parameters:
  learning_rate:
    distribution: log_uniform
    min: -9.21  # log(0.0001)
    max: -2.30  # log(0.1)

  batch_size:
    values: [32, 64, 128]

  dropout:
    distribution: uniform
    min: 0.1
    max: 0.5

  hidden_dim:
    values: [16, 32, 64, 128]

  n_layers:
    values: [1, 2, 3, 4]

early_terminate:
  type: hyperband
  min_iter: 10