# @package dataset
name: "BPI2017"
description: "BPI Challenge 2017 - Application procedure of a Dutch financial institute"
url: "https://data.4tu.nl/articles/dataset/BPI_Challenge_2017/12696884"
direct_download: "https://data.4tu.nl/file/34c3f44b-3101-4ea9-8281-e38905c68b8d/f3aec4f7-d52c-4217-82f4-57d719a8298c"
file_format: "xes.gz"
file_size: "579 MB"
file_name: "BPI Challenge 2017.xes.gz"

