project:
  name: "time_series_benchmarks"
  seed: 42
  wandb_project: "ts_benchmarks"
  wandb:
    enabled: true
    log_predictions: true
    log_hyperparams: true
    tags: []

paths:
  log_dir: "logs"
  data_dir: "data"
  results_dir: "results"

data:
  simple_split: 0.8    # For baseline/statistical
  test_split: 0.2      # For regression/deep_learning
  val_split: 0.2       # For regression/deep_learning
  frequency: "D"       # Daily data

transformations:
  statistical:
    type: "log"
    offset: 1
    epsilon: 1.0e-6
  deep_learning:
    type: "min-max"
  regression:
    type: "none"
  baseline:
    type: "none"

evaluation:
  metrics: ["mae", "rmse"]
  save_predictions: true
  save_models: true